import type { Metadata } from "next";
import MouseLight from "@/components/MouseLight";
import "./globals.css";
import { Funnel_Sans, PT_Sans, Sofia_Sans, Syncopate} from 'next/font/google'
 
const nunito = Funnel_Sans ({
  weight: "400",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Samuel Štofik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={nunito.className} lang="en">
      <body>
        <MouseLight /> 
        <main>{children}</main>
      </body>
    </html>
  );
}
